# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='receiver_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.ContentType', verbose_name='点赞的模型类型, 关联的表名称'),
        ),
        migrations.AlterField(
            model_name='like',
            name='receiver_content_id',
            field=models.PositiveIntegerField(verbose_name='点赞的模型id'),
        ),
        migrations.AlterField(
            model_name='like',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liking', to=settings.AUTH_USER_MODEL, verbose_name='点赞的用户'),
        ),
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='赞的时间'),
        ),
    ]
